version: 2

models:
  - name: staging_orders
    columns:
      - name: order_id
        tests: [not_null, unique]

  - name: staging_riders
    columns:
      - name: rider_id
        tests: [not_null, unique]

  - name: staging_users
    columns:
      - name: user_id
        tests: [not_null, unique]

